### ISSUE TITLE
running basic_reduction_script on simulated one fiber veloce spectra

### ISSUE THREAD

**Issue by blaisekuo** [mq-astrolab/mq_spectrograph#2]
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 100, in <module>
    RON=ronmask, simu=True, savefile=True, filetype='fits', obsname='master_white', path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1091, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 609, in optimal_extraction_from_indices
    for ord in sorted(stripe_indices.iterkeys()):
AttributeError: 'dict' object has no attribute 'iterkeys'

**Comment by blaisekuo** [comment]
looks like stripe_indices isn't as expected

**Comment by JParnell7** [comment]
what does your 'MW_indices' dictionary print out if you were to display it on the screen? my understanding is that the keys from that dictionary (which are the orders) should just be passed into that .iterkeys() statement and the for loop iterates over each order.
but if your 'MW_indices' isn't formed properly, that could be why the error is raised

**Comment by blaisekuo** [comment]
It's a python 2/python3 issue.

iterkeys doesn't exist in python 3. Change instances of iterkeys to keys.

New error:

WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [extraction]
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 100, in <module>
    RON=ronmask, simu=True, savefile=True, filetype='fits', obsname='master_white', path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1091, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 619, in optimal_extraction_from_indices
    fppo = fibparms[ord]
KeyError: 'order_01'

**Comment by blaisekuo** [comment]
the proper encoding is latin1

https://github.com/mq-astrolab/mq_spectrograph/commit/c9ad9a3ec353f58e97d57d79b1da2f8168e44c3a

new error message:

Extracting stellar spectrum 1/6
**ERROR: file shape not correct!!!
ERROR: wrong image size encountered!!!**
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='stellar', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 256, in process_science_images
    img = correct_for_bias_and_dark_from_filename(filename, MB, MD, gain=gain, scalable=scalable, savefile=saveall, path=path, timit=True)   #[e-]
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\calibration.py", line 731, in correct_for_bias_and_dark_from_filename
    bc_img = img - MB
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by JParnell7** [comment]
I also ran into that error the first time I ran the code and changed the following:
- line 256 in process scripts.py, the process science images function has the variable 'img' set to correct_for_bias_and_dark_from_filename(). I had to add in 'simu=True' because that parameter is called in that function if we are using Echelle++ simulated observations.

Let me know if that works and what the next error is that you get, because you might be on the same path I was on.
Also, are there any other lines of code that you had changed to reflect the one-fiber setup that we are using for this spectrograph?

**Comment by blaisekuo** [comment]
So far all the errors have been python and systems issues, so no changes yet concerning the one-fiber setup. But yes, lets keep track of the errors here for future reference.

That works, looks like the default when providing no value for simu is false.

Here's the next error, TOTALEXP isn't in the fits header:

Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='stellar', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 256, in process_science_images
    img = correct_for_bias_and_dark_from_filename(filename, MB, MD, gain=gain, scalable=scalable, savefile=saveall, path=path, simu=True, timit=True)   #[e-]
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\calibration.py", line 738, in correct_for_bias_and_dark_from_filename
    texp = pyfits.getval(imgname, 'TOTALEXP')
  File "C:\ProgramData\Anaconda3\lib\site-packages\astropy\io\fits\convenience.py", line 268, in getval
    return hdr[keyword]
  File "C:\ProgramData\Anaconda3\lib\site-packages\astropy\io\fits\header.py", line 145, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "C:\ProgramData\Anaconda3\lib\site-packages\astropy\io\fits\header.py", line 1654, in _cardindex
    raise KeyError("Keyword {!r} not found.".format(keyword))
KeyError: "Keyword 'TOTALEXP' not found."

**Comment by JParnell7** [comment]
Okay good, I think we are pretty much on the same track.
For this error I found that the headers that our Echelle simulations have do not actually have these 'TOTALEXP' headers, but they have 'exptime' headers instead.
So if you look at lines 737 and 738 in calibration.py, there is code there for both 'exptime' and 'TOTALEXP'. I commented out line 738, and uncommented line 737 so that it reads the 'exptime' header instead.

**Comment by blaisekuo** [comment]
data type problem when generating the quadrant, division by 2 turns them into floats. fix with in calbiration.py:

    q1 = np.zeros((ny, nx), dtype='bool')
    q1[:int(ny / 2), :int(nx / 2)] = True
    q2 = np.zeros((ny, nx), dtype='bool')
    q2[:int(ny / 2), int(nx / 2):] = True
    q3 = np.zeros((ny, nx), dtype='bool')
    q3[int(ny / 2):, int(nx / 2):] = True
    q4 = np.zeros((ny, nx), dtype='bool')
    q4[int(ny / 2):, :int(nx / 2)] = True

next error:

Extracting stellar spectrum 1/6
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='stellar', from_indices=True, timit=True)  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 256, in process_science_images
    img = correct_for_bias_and_dark_from_filename(filename, MB, MD, gain=gain, scalable=scalable, savefile=saveall, path=path, simu=True, timit=True)   #[e-]  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\calibration.py", line 748, in correct_for_bias_and_dark_from_filename
    q1,q2,q3,q4 = make_quadrant_masks(nx,ny)  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\calibration.py", line 71, in make_quadrant_masks
    q1[:(ny / 2), :(nx / 2)] = TrueTypeError: slice indices must be integers or None or have an __index__ method

https://github.com/mq-astrolab/mq_spectrograph/commit/7bdb881be5bde2af799fb54e40140f4bffa5a86c

**Comment by JParnell7** [comment]
Did you run into an error regarding the difference between .fits and .fit? (Shown below)
I had to change line 1151 in extraction.py to say .fit rather than .fits as the data we have to read into it are in .fits format, whereas what we were given was in .fit format.

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-726e7ffe2b9a>", line 154, in <module>
    offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/process_scripts.py", line 287, in process_science_images
    filetype='fits', obsname=obsname, path=path, timit=True)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 1151, in extract_spectrum_from_indices
    h = pyfits.getheader(path+obsname+'.fits')
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/convenience.py", line 110, in getheader
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/convenience.py", line 999, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 1006, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/utils/decorators.py", line 522, in wrapper
    return function(*args, **kwargs)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/util.py", line 395, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: '/Users/Jacob/Desktop/data_for_mq/solar_fib05_0ms.fits'

**Comment by JParnell7** [comment]
this is the next error that pops up when i changed those lines to reflect the .fit/.fits difference:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-726e7ffe2b9a>", line 154, in <module>
    offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/process_scripts.py", line 289, in process_science_images
    RON=ronmask, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True, simu=True) # added simu=True
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 1092, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 829, in optimal_extraction_from_indices
    flux['order_01'][fib] = np.r_[np.repeat(0., 1301), np.squeeze(flux['order_01'][fib])]
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/numpy/lib/index_tricks.py", line 404, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
ValueError: all the input arrays must have same number of dimensions

**Comment by blaisekuo** [comment]
I'm getting an additional error with the path because on my system, the path is in obsname, so it ends up having a double path.

What might be best then is to rename the files we were given to fits. Because the code creates a bunch of files with fits extensions. And I think the code further treats everything as fits.

**Comment by blaisekuo** [comment]
OSError: [Errno 22] Invalid argument: 'd:\\cloudstor\\datastore\\dataredux\\data_for_mq\\d:\\cloudstor\\datastore\\dataredux\\data_for_mq\\solar_fib05_0ms.fits'

replace 37 instances of "path+obsname" with "obsname"

**Comment by blaisekuo** [comment]
Reverted this change, screwed up a bunch of stuff with globally removing path+

**Comment by JParnell7** [comment]
I didn't seem to run into that path issue, however when running step 4 when processing the science images, i ran into this:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-022eec7c3d8d>", line 3, in <module>
    offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/process_scripts.py", line 289, in process_science_images
    RON=ronmask, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True, simu=True) # added simu=True
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 1092, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 829, in optimal_extraction_from_indices
    flux['order_01'][fib] = np.r_[np.repeat(0., 1301), np.squeeze(flux['order_01'][fib])]
  File "/Users/Jacob/Library/Python/2.7/lib/python/site-packages/numpy/lib/index_tricks.py", line 404, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
ValueError: all the input arrays must have same number of dimensions

The lines of code are 825-834 in extraction.py, but is there a reason we are "fixing" anything for the first order?

**Comment by blaisekuo** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\cloudstor\\datastore\\dataredux\\data_for_mq\\solar_fib05_0ms.fits'

change provideds fit files to fits

change in file system and in basic_reduction_script.py

**Comment by JParnell7** [comment]
Christoph mentioned that the "fixing" of order_01 is due to the order not falling on the chip entirely so there is a multitude of problems that arise after that, hence why the code is written. But also said that it should be different for the MQLTS, and that this "fixing" of the first order may not even be an issue at all. Is there any way to confirm that this is the case? If so, then it should just be a simple case of commenting out/removing those lines of code so that the function does not read it

**Comment by blaisekuo** [comment]
ok, i think path issues finally fixed.

next error is from matrix subtrations of a strip and the MB

Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='stellar', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 259, in process_science_images
    img = correct_for_bias_and_dark_from_filename(filename, MB, MD, gain=gain, scalable=scalable, savefile=saveall, path=path, simu=True, timit=True)   #[e-]
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\calibration.py", line 731, in correct_for_bias_and_dark_from_filename
    bc_img = img - MB
ValueError: operands could not be broadcast together with shapes (43,4096) (4096,4096)

**Comment by blaisekuo** [comment]
we can probably ignore the order01 issue since it is a specific issue, unless it already shows up in the sim. We'll need the echelle simulation for the MTLS to check that.

**Comment by JParnell7** [comment]
With your error, just double check that when you first run the code, that there are only 6 items in stellar_list. My issue was that when this file was created (_solar_fib05_0ms_quick_extracted.fits), and i ran into an issue, then re-ran the code, that stellar_list had 7 elements in it. And so this 'extracted' file is actually the strip that causes the error to be thrown. So it is either a case of re-writing output files to a different directory OR just deleting the files that are written to that directory, every time you re-run the code.

As for the order_01 issue, yeah Christoph suggested to change the loop in the function to just start with order_02, rather than comment out or remove that section of code.

**Comment by blaisekuo** [comment]
thanks, yeah i noticed there was suddenly 7 files.

Next error, it looks like the code is expecting 26 fibers:

Oha! Loading NEWest fibre profile parameters...
D:\cloudstor\codestore\dataredux\mq_spectrograph\helper_functions.py:82: RuntimeWarning: divide by zero encountered in true_divide
  phi = np.exp(- (np.absolute(xarr-mu) / (np.sqrt(2.)*sigma)) ** beta)
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='stellar', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 292, in process_science_images
    RON=ronmask, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1091, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 733, in optimal_extraction_from_indices
    phi = make_norm_profiles_5(sr[:, i], i, fppo, integrate=integrate_profiles, slope=slope, offset=offset, fibs=fibs)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\helper_functions.py", line 485, in make_norm_profiles_5
    phi[:, k] = fibmodel(x, mu, sigma, beta=beta, alpha=0, norm=0)
IndexError: index 26 is out of bounds for axis 1 with size 26

**Comment by JParnell7** [comment]
for that error, i can't remember exactly what i did but I think it is to do with the change to one fibre. So we should pass the "fibs" parameter for step 4 as 'single' rather than 'stellar'

**Comment by JParnell7** [comment]
current error:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-022eec7c3d8d>", line 3, in <module>
    offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "/Users/Jacob/Desktop/mq_spectrograph_local/process_scripts.py", line 289, in process_science_images
    RON=ronmask, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True, simu=True) # added simu=True
  File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 1145, in extract_spectrum_from_indices
    fluxarr[i,j,:] = flux[o][fib]
ValueError: setting an array element with a sequence.

**Comment by blaisekuo** [comment]
'single' throws up a non terminating error, it's unrecognized in extraction.py for optimal extraction and the default is 24:

ERROR: fibre selection not recognised!!!
Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 292, in process_science_images
    RON=ronmask, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1091, in extract_spectrum_from_indices
    fibpos=fibpos, simu=simu, timit=timit, debug_level=debug_level)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 748, in optimal_extraction_from_indices
    f, v = linalg_extract_column(z, pix_w, phi, RON=np.mean(roncol))
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\linalg.py", line 19, in linalg_extract_column
    C = np.matmul( np.matmul(np.transpose(phi),w_mat), phi )
TypeError: Object arrays are not currently supported

**Comment by JParnell7** [comment]
double check that 'simu=True' is passed in line 292 in 'process_science_images' and see if an error is thrown

**Comment by blaisekuo** [comment]
I did leave it out of quick extraction,b ut it was set to True for optimal extraction. I change them both the simu=True

But process image doesn't have a simu declaration

def process_science_images(imglist, P_id, mask=None, sampling_size=25, slit_height=25, gain=[1.,1.,1.,1.], MB=None, ronmask=None, MD=None, scalable=False, saveall=False, path=None, ext_method='optimal', 
                           from_indices=True, slope=True, offset=True, fibs='all', timit=False):

**Comment by blaisekuo** [comment]
ah, there is a extract_spectrum_from_indices call in there.

**Comment by blaisekuo** [comment]
We've reached about the same spot. There's an error in extraction.py line 1091. Looks like that should be a simu=True instead of simu=simu

**Comment by JParnell7** [comment]
I'm not sure changing that matters as when we run the functions, we pass 'simu=True' anyway, so if 'simu=simu', it should just pass 'simu=True' irrespective?

**Comment by blaisekuo** [comment]
Yeah, it would only have failed if we didn't pass in a value.

**Comment by JParnell7** [comment]
the current error im running into:
File "/Users/Jacob/Desktop/mq_spectrograph_local/extraction.py", line 1145, in extract_spectrum_from_indices
    fluxarr[i,j,:] = flux[o][fib]
ValueError: setting an array element with a sequence.

I dont understand why it fails, as the lines of code preceding it are all if statements which are satisfied when I run step 4, and so the "fluxarr" and "errarr" arrays should be able to form. When i run those lines of code outside the function, the code seems to work, but when in the loop it seems to throw up the ValueError.

I tried to change the array by passing "dtype=object" but then an error is thrown in step 3, and I can't even get to step 4.

**Comment by blaisekuo** [comment]
mine has a bit more info the error message:

Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 100, in <module>
    RON=ronmask, simu=True, savefile=True, filetype='fits', obsname='master_white', path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1134, in extract_spectrum_from_indices
    fluxarr[i,j,:] = flux[o][fib]
ValueError: cannot copy sequence with size 2795 to array axis with dimension 4096

**Comment by JParnell7** [comment]
I think I ran into that error earlier, but I don't remember how I fixed it. However I think the next step I took was as per Christoph's advice which was to amend any loops in any of the subroutines so that it skips order_01.

For example, I added in the following lines of code underneath any for loop that iterates over a dictionary with the orders set as the keys. Such as "for ord in sorted(stripes.keys()):" on line 51 in extraction.py.
if ord == 'order_01:
     continue

And added the same for a few subroutines in the order_tracing.py file. Because it avoids the specific "order_01" issue mentioned yesterday. Hopefully when that is fixed, we should be on the same issue.

**Comment by blaisekuo** [comment]
ok. I tried to treat order01 the same way by commenting out the handling for it. I'll try this by skipping it instead.

**Comment by blaisekuo** [comment]
I made two two edits in extraction.py to prevent goodrange from being resized. So that order_01 gets treated like any other order.


https://github.com/mq-astrolab/mq_spectrograph/commit/851962ac6185617d68fd34cc3be7ab547ce376ea

**Comment by blaisekuo** [comment]
Next error:

Traceback (most recent call last):
  File ".\basic_reduction_script.py", line 128, in <module>
    saveall=False, path=path, ext_method='optimal', offset='True', slope='True', fibs='single', from_indices=True, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\process_scripts.py", line 292, in process_science_images
    RON=ronmask, simu=True, savefile=True, filetype='fits', obsname=obsname, path=path, timit=True)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 1099, in extract_spectrum_from_indices
    fibpos=fibpos, simu=True, timit=timit, debug_level=debug_level)
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\extraction.py", line 754, in optimal_extraction_from_indices
    f, v = linalg_extract_column(z, pix_w, phi, RON=np.mean(roncol))
  File "D:\cloudstor\codestore\dataredux\mq_spectrograph\linalg.py", line 32, in linalg_extract_column
    C_inv = np.linalg.inv(C)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 528, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

**Comment by JParnell7** [comment]
I am unsure about that issue - I have just uploaded in a new branch, my files that I have now which seem to run for the quick extraction method. However when running the optimal extraction method, the code seems to crash. Having spoken with Richard, due to our time constraint of the scholarship, we are wanting to try to move forward even if it is with these files that are extracted using a 'quick' method.

Perhaps seeing if there are any discrepancies between your code and the ones I just uploaded, may resolve the error in regards to the changes you made to extraction.py for order_01? And from this, solutions could be found as to why the optimal method seems to crash, but the quick method doesn't.
